llm_chat:
  type: LlamaCpp
  identifier: TheBloke/Mistral-7B-Instruct-v0.1-GGUF  # Update with actual model identifier
  filename: mistral-7b-instruct-v0.1.Q4_K_M.gguf      # Update with actual model filename
  n_gpu_layers: -1 # -1 means all layers

#  type: Transformers
#  model: mistralai/Mistral-7B-Instruct-v0.1

#  type: OpenAI
#  model: gpt-3.5-turbo-1106 # Replace with the model you want to use
#  api_key: YOUR_OPENAI_API_KEY  # Replace with your actual API key

llm_completion:
  type: LlamaCpp
  identifier: TheBloke/Mistral-7B-Instruct-v0.1-GGUF  # Update with actual model identifier
  filename: mistral-7b-instruct-v0.1.Q4_K_M.gguf      # Update with actual model filename
  n_gpu_layers: -1 # -1 means all layers

#  type: Transformers
#  model: mistralai/Mistral-7B-Instruct-v0.1

#  type: OpenAI
#  model: gpt-3.5-turbo-instruct # Replace with the model you want to use
#  api_key: YOUR_OPENAI_API_KEY  # Replace with your actual API key